export const REQUEST_MASTER_EVENT = "REQUEST_MASTER_EVENT";
export const SET_MASTER_EVENT = "SET_MASTER_EVENT";
export const ERROR_GET_MASTER_EVENT = "ERROR_GET_MASTER_EVENT";

export const REQUEST_CREATE_MASTER_EVENT = "REQUEST_CREATE_MASTER_EVENT";
export const SUCCESS_CREATE_MASTER_EVENT = "SUCCESS_CREATE_MASTER_EVENT";
export const ERROR_CREATE_MASTER_EVENT = "ERROR_CREATE_MASTER_EVENT";

export const REQUEST_UPDATE_MASTER_EVENT = "REQUEST_UPDATE_MASTER_EVENT";
export const SUCCESS_UPDATE_MASTER_EVENT = "SUCCESS_UPDATE_MASTER_EVENT";
export const ERROR_UPDATE_MASTER_EVENT = "ERROR_UPDATE_MASTER_EVENT";

export const REQUEST_DELETE_MASTER_EVENT = "REQUEST_DELETE_MASTER_EVENT";
export const SUCCESS_DELETE_MASTER_EVENT = "SUCCESS_DELETE_MASTER_EVENT";
export const ERROR_DELETE_MASTER_EVENT = "ERROR_DELETE_MASTER_EVENT";

export const SET_MESSAGE_MASTER_EVENT = "SET_MESSAGE_MASTER_EVENT";