export const REQUEST_MASTER_OUR_CLIENTS = "REQUEST_MASTER_OUR_CLIENTS";
export const SET_MASTER_OUR_CLIENTS = "SET_MASTER_OUR_CLIENTS";
export const ERROR_GET_MASTER_OUR_CLIENTS = "ERROR_GET_MASTER_OUR_CLIENTS";

export const REQUEST_CREATE_MASTER_OUR_CLIENTS = "REQUEST_CREATE_MASTER_OUR_CLIENTS";
export const REQUEST_CREATE_MASTER_OUR_CLIENTS_STORY = "REQUEST_CREATE_MASTER_OUR_CLIENTS_STORY";
export const SUCCESS_CREATE_MASTER_OUR_CLIENTS = "SUCCESS_CREATE_MASTER_OUR_CLIENTS";
export const SUCCESS_CREATE_MASTER_OUR_CLIENTS_STORY = "SUCCESS_CREATE_MASTER_OUR_CLIENTS_STORY";
export const ERROR_CREATE_MASTER_OUR_CLIENTS = "ERROR_CREATE_MASTER_OUR_CLIENTS";
export const ERROR_CREATE_MASTER_OUR_CLIENTS_STORY = "ERROR_CREATE_MASTER_OUR_CLIENTS_STORY";

export const REQUEST_UPDATE_MASTER_OUR_CLIENTS = "REQUEST_UPDATE_MASTER_OUR_CLIENTS";
export const REQUEST_UPDATE_MASTER_OUR_CLIENTS_STORY = "REQUEST_UPDATE_MASTER_OUR_CLIENTS_STORY";
export const SUCCESS_UPDATE_MASTER_OUR_CLIENTS = "SUCCESS_UPDATE_MASTER_OUR_CLIENTS";
export const SUCCESS_UPDATE_MASTER_OUR_CLIENTS_STORY = "SUCCESS_UPDATE_MASTER_OUR_CLIENTS_STORY";
export const ERROR_UPDATE_MASTER_OUR_CLIENTS = "ERROR_UPDATE_MASTER_OUR_CLIENTS";
export const ERROR_UPDATE_MASTER_OUR_CLIENTS_STORY = "ERROR_UPDATE_MASTER_OUR_CLIENTS_STORY";

export const REQUEST_DELETE_MASTER_OUR_CLIENTS = "REQUEST_DELETE_MASTER_OUR_CLIENTS";
export const REQUEST_DELETE_MASTER_OUR_CLIENTS_STORY = "REQUEST_DELETE_MASTER_OUR_CLIENTS_STORY";
export const SUCCESS_DELETE_MASTER_OUR_CLIENTS = "SUCCESS_DELETE_MASTER_OUR_CLIENTS";
export const SUCCESS_DELETE_MASTER_OUR_CLIENTS_STORY = "SUCCESS_DELETE_MASTER_OUR_CLIENTS_STORY";
export const ERROR_DELETE_MASTER_OUR_CLIENTS = "ERROR_DELETE_MASTER_OUR_CLIENTS";
export const ERROR_DELETE_MASTER_OUR_CLIENTS_STORY = "ERROR_DELETE_MASTER_OUR_CLIENTS_STORY";

export const SET_MESSAGE_MASTER_OUR_CLIENTS = "SET_MESSAGE_MASTER_OUR_CLIENTS";