export const REQUEST_USERS = "REQUEST_USERS";
export const SET_USERS = "SET_USERS";
export const ERROR_USERS = "ERROR_USERS";

export const REQUEST_BLOCK_USERS = "REQUEST_BLOCK_USERS";
export const SUCCESS_BLOCK_USERS = "SUCCESS_BLOCK_USERS";
export const ERROR_BLOCK_USERS = "ERROR_BLOCK_USERS";