export const REQUEST_MASTER_CATEGORIES = "REQUEST_MASTER_CATEGORIES";
export const SET_MASTER_CATEGORIES = "SET_MASTER_CATEGORIES";
export const ERROR_GET_MASTER_CATEGORIES = "ERROR_GET_MASTER_CATEGORIES";

export const REQUEST_CREATE_MASTER_CATEGORIES = "REQUEST_CREATE_MASTER_CATEGORIES";
export const SUCCESS_CREATE_MASTER_CATEGORIES = "SUCCESS_CREATE_MASTER_CATEGORIES";
export const ERROR_CREATE_MASTER_CATEGORIES = "ERROR_CREATE_MASTER_CATEGORIES";

export const REQUEST_UPDATE_MASTER_CATEGORIES = "REQUEST_UPDATE_MASTER_CATEGORIES";
export const SUCCESS_UPDATE_MASTER_CATEGORIES = "SUCCESS_UPDATE_MASTER_CATEGORIES";
export const ERROR_UPDATE_MASTER_CATEGORIES = "ERROR_UPDATE_MASTER_CATEGORIES";

export const REQUEST_DELETE_MASTER_CATEGORIES = "REQUEST_DELETE_MASTER_CATEGORIES";
export const SUCCESS_DELETE_MASTER_CATEGORIES = "SUCCESS_DELETE_MASTER_CATEGORIES";
export const ERROR_DELETE_MASTER_CATEGORIES = "ERROR_DELETE_MASTER_CATEGORIES";

export const SET_MESSAGE_MASTER_CATEGORIES = "SET_MESSAGE_MASTER_CATEGORIES";