export const REQUEST_MASTER_NEWS = "REQUEST_MASTER_NEWS";
export const SET_MASTER_NEWS = "SET_MASTER_NEWS";
export const ERROR_GET_MASTER_NEWS = "ERROR_GET_MASTER_NEWS";

export const REQUEST_CREATE_MASTER_NEWS = "REQUEST_CREATE_MASTER_NEWS";
export const SUCCESS_CREATE_MASTER_NEWS = "SUCCESS_CREATE_MASTER_NEWS";
export const ERROR_CREATE_MASTER_NEWS = "ERROR_CREATE_MASTER_NEWS";

export const REQUEST_UPDATE_MASTER_NEWS = "REQUEST_UPDATE_MASTER_NEWS";
export const SUCCESS_UPDATE_MASTER_NEWS = "SUCCESS_UPDATE_MASTER_NEWS";
export const ERROR_UPDATE_MASTER_NEWS = "ERROR_UPDATE_MASTER_NEWS";

export const REQUEST_DELETE_MASTER_NEWS = "REQUEST_DELETE_MASTER_NEWS";
export const SUCCESS_DELETE_MASTER_NEWS = "SUCCESS_DELETE_MASTER_NEWS";
export const ERROR_DELETE_MASTER_NEWS = "ERROR_DELETE_MASTER_NEWS";

export const SET_MESSAGE_MASTER_NEWS = "SET_MESSAGE_MASTER_NEWS";